[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10.5

[font.bold]
family = "Hurmit Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hurmit Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hurmit Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hurmit Nerd Font Mono"
style = "Regular"
