
[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/settings/window.toml",
    "~/.config/alacritty/settings/cursor.toml",
    "~/.config/alacritty/settings/fonts.toml",
    "~/.config/alacritty/settings/colors.toml",
    "~/.config/alacritty/settings/theme.toml"
]
